#-------------------------------
# Site Settings
title: Meredith Cook
logo: # You can add own logo. For example '/images/logo.png'.
description: Personal website and blog
baseurl: # the subpath of your site, e.g. /blog
url: "https://meredithcook.net" # the base hostname & protocol for your site, e.g. http://example.com
color_scheme: auto # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the user can choose the light or dark mode themself.


#-------------------------------
# Author Settings
author:
  author__name: Meredith Cook
  author__bio: Mom. Grant Writer. Author.
  author__avatar: '/images/headshot_MC.png'

social:
- {icon: "ion-logo-twitter", link: "https://twitter.com/meredithcook716"}
- {icon: "ion-logo-linkedin", link: "https://www.linkedin.com/in/meredithcook716/"}
- {icon: "ion-logo-pinterest", link: "https://www.pinterest.com/meredithlcook/"}
- {icon: "ion-md-book", link: "https://amzn.to/45wlDh1"}

# Example of adding a new link to the footer - {icon: "ion-logo-dribbble", link: "https://dribbble.com"}
# Other icons can be found at https://ionicons.com/v4/


#-------------------------------
# Hero Settings
hero:
  hero__title: Welcome! I'm Meredith Cook.
  hero__description: I'm a stay-at-home mom moonlighting as a writer of grants and children's books.
  hero__image: '/images/headshot_MC.png'


#-------------------------------
# Newsletter
mailchimp: # To enable the mailchimp form, use the value 'enable'. To disable the form, leave the field blank.
mailchimp__identifier: frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3 # Add your MailChimp form identifier. For example - frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3
mailchimp__input__text: Subscribe here
mailchimp__button__text: Get a new tip


#-------------------------------
# Gallery Footer Section
gallery:
  gallery__title: Gallery
  gallery__columns: 3
  gallery__images:
    - alt: 'Torrey Pines'
      url: '/images/torrey_pines.jpeg'
    - alt: 'Big Bend'
      url: '/images/big_bend.jpeg'
    - alt: 'West Virginia'
      url: '/images/west_virginia.jpeg'
    - alt: 'Tokyo'
      url: '/images/tokyo.jpeg'
    - alt: 'Grand Canyon'
      url: '/images/grand_canyon.jpeg'
    - alt: 'Paris'
      url: '/images/paris.jpeg'
    - alt: 'Japan'
      url: '/images/japan.jpeg'
    - alt: 'India'
      url: '/images/india.jpeg'
    - alt: 'Istanbul'
      url: '/images/istanbul.jpeg'


#-------------------------------
# Contact Settings
contact:
  email: meredithcook@proton.me # Add your email for contant form
  description: To contact me with questions or comments, please fill out the form below. # Add a description of your form

# NOTE
# Menca theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


#-------------------------------
# Comment Section (Disqus)
disqus-identifier:  # Add your shortname for Disqus Comment. For example demo-menca


#-------------------------------
# Google Analytics
google-analytics: # Add your GA Tracking Id


#-------------------------------
# Build Settings
markdown: kramdown
permalink: /:title
plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 9
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext


include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed
